name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the following information to help us reproduce and fix the issue.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Existing Issues
      description: Please search existing issues before creating a new one
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Initialize SyncEngine with...
        2. Call method...
        3. See error...
      value: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      placeholder: |
        ```typescript
        import { SyncEngine } from 'sync-engine-lib';

        const syncEngine = new SyncEngine({
          // your config
        });

        // code that reproduces the bug
        ```
      render: typescript

  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which package is affected?
      options:
        - sync-engine-lib
        - demo-app
        - demo-server
        - documentation
        - other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running on?
      multiple: true
      options:
        - React Native (iOS)
        - React Native (Android)
        - Expo (iOS)
        - Expo (Android)
        - Node.js
        - Web
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide environment details
      placeholder: |
        - OS: [e.g. iOS 15.0, Android 12, macOS 12.0]
        - Node.js version: [e.g. 18.17.0]
        - React Native version: [e.g. 0.72.0]
        - Expo SDK version: [e.g. 49.0.0]
        - Device: [e.g. iPhone 13, Pixel 6]
      value: |
        - OS: 
        - Node.js version: 
        - React Native version: 
        - Expo SDK version: 
        - Device:
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages / Stack Trace
      description: Please include any error messages or stack traces
      placeholder: Paste error messages and stack traces here...
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Network conditions
        - Data size
        - Frequency of the issue
        - Workarounds you've tried
        - Related issues

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: How does this bug affect your usage?
      options:
        - label: Blocks development
        - label: Causes crashes
        - label: Data loss or corruption
        - label: Performance issues
        - label: Minor inconvenience

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - Low - Nice to have
        - Medium - Important for next release
        - High - Blocks major functionality
        - Critical - Security or data loss issue
    validations:
      required: true
