name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build library
        run: yarn workspace sync-engine-lib build
        
      - name: Run tests
        run: yarn workspace sync-engine-lib test --coverage
        
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./packages/sync-engine-lib/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Run ESLint
        run: yarn workspace sync-engine-lib lint
        
      - name: Check TypeScript
        run: yarn workspace sync-engine-lib build

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Run security audit (root)
        run: yarn audit --level moderate
        continue-on-error: true
        
      - name: Run security audit (library)
        run: yarn workspace sync-engine-lib audit --level moderate
        continue-on-error: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build library
        run: yarn workspace sync-engine-lib build
        
      - name: Check build output
        run: ls -la packages/sync-engine-lib/dist/
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files-node-${{ github.run_id }}
          path: packages/sync-engine-lib/dist/

  demo-build:
    name: Demo Apps Build Check
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build library first
        run: yarn workspace sync-engine-lib build
        
      - name: Check demo-server dependencies
        run: yarn workspace demo-server install --check-files
        
      - name: Check demo-app dependencies  
        run: yarn workspace demo-app install --check-files